package httpapi

import (
	"context"

	"ecommerce/internal/apicontract"
)

// LocalizationStrictServer is the exact generated strict subset owned by the
// platform-wide localization subsystem.
type LocalizationStrictServer interface {
	ListLocalizationLocales(context.Context, apicontract.ListLocalizationLocalesRequestObject) (apicontract.ListLocalizationLocalesResponseObject, error)
	GetLocalizationBundle(context.Context, apicontract.GetLocalizationBundleRequestObject) (apicontract.GetLocalizationBundleResponseObject, error)
	GetLocalizationBundleMeta(context.Context, apicontract.GetLocalizationBundleMetaRequestObject) (apicontract.GetLocalizationBundleMetaResponseObject, error)
	GetAdminLocalizationReleaseQuality(context.Context, apicontract.GetAdminLocalizationReleaseQualityRequestObject) (apicontract.GetAdminLocalizationReleaseQualityResponseObject, error)
	RollbackAdminLocalizationRelease(context.Context, apicontract.RollbackAdminLocalizationReleaseRequestObject) (apicontract.RollbackAdminLocalizationReleaseResponseObject, error)
	ListAdminLocalizationLocales(context.Context, apicontract.ListAdminLocalizationLocalesRequestObject) (apicontract.ListAdminLocalizationLocalesResponseObject, error)
	ReplaceAdminLocalizationLocales(context.Context, apicontract.ReplaceAdminLocalizationLocalesRequestObject) (apicontract.ReplaceAdminLocalizationLocalesResponseObject, error)
	ListAdminLocalizationKeys(context.Context, apicontract.ListAdminLocalizationKeysRequestObject) (apicontract.ListAdminLocalizationKeysResponseObject, error)
	CreateAdminLocalizationKey(context.Context, apicontract.CreateAdminLocalizationKeyRequestObject) (apicontract.CreateAdminLocalizationKeyResponseObject, error)
	ListAdminLocalizationValues(context.Context, apicontract.ListAdminLocalizationValuesRequestObject) (apicontract.ListAdminLocalizationValuesResponseObject, error)
	ListAdminLocalizationKeyUsages(context.Context, apicontract.ListAdminLocalizationKeyUsagesRequestObject) (apicontract.ListAdminLocalizationKeyUsagesResponseObject, error)
	ReplaceAdminLocalizationKeyUsages(context.Context, apicontract.ReplaceAdminLocalizationKeyUsagesRequestObject) (apicontract.ReplaceAdminLocalizationKeyUsagesResponseObject, error)
	PutAdminLocalizationValue(context.Context, apicontract.PutAdminLocalizationValueRequestObject) (apicontract.PutAdminLocalizationValueResponseObject, error)
	SubmitAdminLocalizationValueReview(context.Context, apicontract.SubmitAdminLocalizationValueReviewRequestObject) (apicontract.SubmitAdminLocalizationValueReviewResponseObject, error)
	PublishAdminLocalizationValue(context.Context, apicontract.PublishAdminLocalizationValueRequestObject) (apicontract.PublishAdminLocalizationValueResponseObject, error)
	ListAdminLocalizationComments(context.Context, apicontract.ListAdminLocalizationCommentsRequestObject) (apicontract.ListAdminLocalizationCommentsResponseObject, error)
	CreateAdminLocalizationComment(context.Context, apicontract.CreateAdminLocalizationCommentRequestObject) (apicontract.CreateAdminLocalizationCommentResponseObject, error)
	ListAdminLocalizationReleases(context.Context, apicontract.ListAdminLocalizationReleasesRequestObject) (apicontract.ListAdminLocalizationReleasesResponseObject, error)
	CreateAdminLocalizationRelease(context.Context, apicontract.CreateAdminLocalizationReleaseRequestObject) (apicontract.CreateAdminLocalizationReleaseResponseObject, error)
	ActivateAdminLocalizationRelease(context.Context, apicontract.ActivateAdminLocalizationReleaseRequestObject) (apicontract.ActivateAdminLocalizationReleaseResponseObject, error)
	ImportAdminLocalization(context.Context, apicontract.ImportAdminLocalizationRequestObject) (apicontract.ImportAdminLocalizationResponseObject, error)
	ExportAdminLocalization(context.Context, apicontract.ExportAdminLocalizationRequestObject) (apicontract.ExportAdminLocalizationResponseObject, error)
	ListAdminLocalizationGlossary(context.Context, apicontract.ListAdminLocalizationGlossaryRequestObject) (apicontract.ListAdminLocalizationGlossaryResponseObject, error)
	PutAdminLocalizationGlossaryTerm(context.Context, apicontract.PutAdminLocalizationGlossaryTermRequestObject) (apicontract.PutAdminLocalizationGlossaryTermResponseObject, error)
	DeleteAdminLocalizationGlossaryTerm(context.Context, apicontract.DeleteAdminLocalizationGlossaryTermRequestObject) (apicontract.DeleteAdminLocalizationGlossaryTermResponseObject, error)
	ListAdminLocalizationRoles(context.Context, apicontract.ListAdminLocalizationRolesRequestObject) (apicontract.ListAdminLocalizationRolesResponseObject, error)
	PutAdminLocalizationRole(context.Context, apicontract.PutAdminLocalizationRoleRequestObject) (apicontract.PutAdminLocalizationRoleResponseObject, error)
	ListAdminLocalizationAssignees(context.Context, apicontract.ListAdminLocalizationAssigneesRequestObject) (apicontract.ListAdminLocalizationAssigneesResponseObject, error)
	ListAdminLocalizationRollouts(context.Context, apicontract.ListAdminLocalizationRolloutsRequestObject) (apicontract.ListAdminLocalizationRolloutsResponseObject, error)
	ReplaceAdminLocalizationRollouts(context.Context, apicontract.ReplaceAdminLocalizationRolloutsRequestObject) (apicontract.ReplaceAdminLocalizationRolloutsResponseObject, error)
	GetAdminLocalizationMetrics(context.Context, apicontract.GetAdminLocalizationMetricsRequestObject) (apicontract.GetAdminLocalizationMetricsResponseObject, error)
	GetAdminEntityLocalization(context.Context, apicontract.GetAdminEntityLocalizationRequestObject) (apicontract.GetAdminEntityLocalizationResponseObject, error)
	PutAdminEntityLocalization(context.Context, apicontract.PutAdminEntityLocalizationRequestObject) (apicontract.PutAdminEntityLocalizationResponseObject, error)
}

var _ LocalizationStrictServer = (*LocalizationEndpoints)(nil)
